blank_issues_enabled: false
contact_links:
  - name: ❓ Other Red Hat Developer Hub issues (JIRA)
    url: https://issues.redhat.com/browse/RHDHBUGS
    about: Use JIRA for product issues and feature requests; GitHub issue templates in this repository are for automation requests.
  - name: ❓ Red Hat Developer Hub Plugins
    url: https://issues.redhat.com/browse/RHDHBUGS
    about: Please report any issues with https://github.com/redhat-developer/rhdh-plugins in JIRA - https://issues.redhat.com/browse/RHDHBUGS
  - name: ❓ Backstage Community Plugins
    url: https://github.com/backstage/community-plugins/issues
    about: Please report any plugin issues or feature requests in https://github.com/backstage/community-plugins/issues
